- name: "add ses verification entry"
  route53:
    zone: "{{domain_name}}"
    record: "_amazonses.{{domain_name}}"
    type: "TXT"
    ttl: "{{ttl|default(86400)}}"
    value: '"{{aws_ses_verification}}"'
    command: create
  when: blok_anan_state == "present"
- name: "add dkim entries"
  route53:
    zone: "{{domain_name}}"
    record: "{{item.src}}.{{domain_name}}"
    type: "CNAME"
    value: '"{{item.dest}}"'
    command: create
  with_items: "{{aws_ses_dkim}}"
  when: blok_anan_state == "present"